### ISSUE TITLE
Chyba generování článků

### ISSUE THREAD

**Issue by PetraDundacek** [vlastami/SWI#15]
Po vložení chybného odkazu se přestávají generovat náhledy článků u těch odkazů, které následují po chybném (byť jsou vloženy správně).
![Bug](https://github.com/vlastami/SWI/assets/91459165/7f725d03-1bcd-425b-8bf6-81d0a9678352)

**Comment by mmelicher91** [comment]
Ahoj,
ta chyba se netýká jen špatného odkazu. Duplikují se nám tam záznamy a pak je to celý posunutý.
